### PR TITLE
Update to match hledger 1.25's error messages

### PR DESCRIPTION
**Pull request by simonmichael**

### CODE REVIEW

**Review by DamienCassou — CHANGES_REQUESTED** [review]
thank you very much for your contribution @simonmichael. I appreciate it. In its current state, your PR is hard to review because it changes many things at once. Could you please create separate commits for separate changes? E.g., the addition of the `:modes` argument, the changes in comments and the changes in patterns. I'm quite a proponent of atomic commits.

Thank you very much

**Comment by simonmichael** [comment]
Sorry the change is unclear. Does it help if I describe it: 
- Updated your error patterns to match hledger 1.25's error messages ('"FILE" (lines A-B)' -> 'FILE:A-B', etc.)
- Moved a couple of other properties towards the top, ordering them from high-level to low-level
- About 20 lines affected
?

**Comment by simonmichael** [comment]
PS I expect more changes will be needed, as hledger errors improve, so no hurry to merge this if you'd rather wait. When I next have time perhaps I can redo .

**Comment by simonmichael** [comment]
New changes pushed and ready for review.

**Review by DamienCassou — APPROVED** [review]
Much better, thank you very much!

**Comment by DamienCassou** [comment]
Excellent work. I think it's important that the code follows the releases so I'm going to merge this. Thank you

**Comment by DamienCassou** [comment]
I think this patch is triggering https://github.com/DamienCassou/flycheck-hledger/issues/11.

**Pull request merged**
