### PR TITLE
Update makel URL

### PR DESCRIPTION
**Pull request by doolio**

### CODE REVIEW

**Comment by DamienCassou** [comment]
@doolio To make sure I never miss your PRs, I suggest you assign me as reviewer if you can: 
image

**Comment by DamienCassou** [comment]
Thanks again

**Comment by doolio** [comment]
> To make sure I never miss your PRs, I suggest you assign me as reviewer if you can:

Will do. I assumed you are automatically notified as the repository owner.

**Comment by DamienCassou** [comment]
I get an email for each PR. But with many PRs, I might get confused and archive an email for a PR I haven't merged yet. If I'm assign to a PR, it will stay in my todo list until I'm done with it.

**Comment by doolio** [comment]
> To make sure I never miss your PRs, I suggest you assign me as reviewer if you can:

It seems this feature is only available to the repository owner and not the author of a particular PR. This is what I see with no gear icon to change the settings.

image

I can only @DamienCassou mention you in an issue/PR but I don't know if that adds an entry to your (github) todo list.

**Comment by DamienCassou** [comment]
I was afraid of that. Thanks for telling me.

**Pull request merged**
